### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by stingalleman** [inversify/inversify.github.io#15]
If you're hosting this site with GH pages, it's really simple to enable HTTPS. Users are getting errors saying 'Connection not secure' and that's not really professional.

**Comment by dcavanagh** [comment]
@stingalleman thank you. There is a problem with the custom domain and I do not have access to update the ip addresses

**Comment by stingalleman** [comment]
I don't think you need to update the IP for HTTPS support? Not sure tho.

**Comment by dcavanagh** [comment]
It wasn't letting me turn on https until the DNS was updated. The owner just updated the DNS record and it is now enabled.
